import React from 'react';
import ReactBlueImp from './../components/ReactBlueImpGallery';
import './_CustomReactSlide.css';

class CustomReactSlide extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      source: [{
        source: 'images/banana.jpg',
        thumbnail: 'images/thumbnails/banana.jpg',
        title: 'Bananas',
        'data-description': '🍌🍌🍌',
      }, {
        source: 'images/apples.jpg',
        thumbnail: 'images/thumbnails/apples.jpg',
        title: 'Apples',
        'data-description': '🍎🍎🍎',
      }, {
        source: 'images/orange.jpg',
        thumbnail: 'images/thumbnails/orange.jpg',
        title: 'Oranges',
        'data-description': '🍊🍊🍊',
      }],
      slideCount: 0,
    };
  }
  render() {
    return (
      <ReactBlueImp
        options={{
          onslide: () => this.setState({ slideCount: this.state.slideCount + 1 }),
          onclose: () => this.setState({ slideCount: 0 }),
        }}
        withControls
      >

        <ReactBlueImp.Slide
          source="images/thumbnails/banana.jpg"
          type="text/react"
          key="MyAutoUpdateSlideContent"
        >
          <MyReactStaticSlideContent />
        </ReactBlueImp.Slide>

        <ReactBlueImp.Slide
          source="images/thumbnails/apples.jpg"
          type="text/react"
          synchedData={{ slideCount: this.state.slideCount }}
          key="MySynchedDataSlideContent"
        >
          <MyAutoUpdateSlideContent />
        </ReactBlueImp.Slide>

        <ReactBlueImp.Slide
          source="images/thumbnails/orange.jpg"
          type="text/react"
          key="MyReactStaticSlideContent"
        >
          <MySynchedDataSlideContent />
        </ReactBlueImp.Slide>
      </ReactBlueImp>
    );
  }
}

class MySynchedDataSlideContent extends React.Component {
  render() {
    const {
      slideCount,
    } = this.props;
    return <div className="react-slide">
      <p style={{ color: 'white' }}>
        DISPLAYED SLIDES COUNT: {slideCount}<br/>
        <span style={{ fontSize: 15 }}>This content updates from parent component state, linked to onslide action of BlueImp Gallery.</span>
      </p>

    </div>;
  }
}

class MyAutoUpdateSlideContent extends React.Component {
  constructor(props) {
    super(props);
    this.tick = this.tick.bind(this);
    this.state = {
      count: 0,
    };
  }

  tick() {
    this.setState({ count: this.state.count + 1 });
  }

  componentDidMount() {
    this.interval = setInterval(this.tick, 1000);
  }

  componentWillUnmount() {
    clearInterval(this.interval);
  }

  render() {
    return <div className="react-slide">
      <p style={{ color: 'white' }}>
        AUTO UPDATES: {this.state.count}<br/>
        <span style={{ fontSize: 15 }}>This content updates from a timer triggered inside the same component.</span>
      </p>
    </div>;
  }
}

class MyReactStaticSlideContent extends React.Component {
  render() {
    return <div className="react-slide">
      <p style={{ color: 'white' }}>
        STATIC CONTENT<br/>
        This content is generated by a React component.
      </p>
    </div>;
  }
}
export default CustomReactSlide;
